---
title: Raspbian installeren met NOOBS
hero_image: images / banner.png
description: Een gids over het installeren van Raspbian op een SD-kaart met behulp van NOOBS, vanaf elk platform
original_url: https://raspberrypi.org/learning/noobs-install
theme: rood
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: maker, ontwerp-0, programmeren-0, phys-comp-0, productie-0, community-0
interests: ''
technologies: rpi, fysieke computergebruik, python
site_areas: ''
steps:
  - 
    title: Invoering
