---
title: Installing Raspbian with NOOBS
hero_image: images/banner.png
description: A guide on how to install Raspbian on an SD card using NOOBS, from any
  platform
original_url: https://raspberrypi.org/learning/noobs-install
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Installing Raspbian using NOOBS
- title: Downloading NOOBS
- title: 'Writing NOOBS to an SD Card: Which OS?'
- title: Booting from NOOBS
- title: What next?

