---
title: Instalando Raspbian con NOOBS
hero_image: images / banner.png
description: Una guía sobre cómo instalar Raspbian en una tarjeta SD usando NOOBS, desde cualquier plataforma
original_url: https://raspberrypi.org/learning/noobs-install
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: creador, diseño-0, programación-0, phys-comp-0, fabricación-0, comunidad-0
interests: ''
technologies: rpi, informática física, pitón
site_areas: ''
steps:
  - 
    title: Introducción
