---
title: Installation af Raspbian med NOOBS
hero_image: images / banner.png
description: En guide til, hvordan du installerer Raspbian på et SD-kort ved hjælp af NOOBS, fra enhver platform
original_url: https://raspberrypi.org/learning/noobs-install
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: skaber, design-0, programmering-0, phys-comp-0, fremstilling-0, community-0
interests: ''
technologies: rpi, fysisk databehandling, python
site_areas: ''
steps:
  - 
    title: Introduktion
