---
title: 用NOOBS安装Raspbian
hero_image: 图片/ banner.png
description: 关于如何在任何平台上使用NOOBS在SD卡上安装Raspbian的指南
original_url: https://raspberrypi.org/learning/noobs-install
theme: 红
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: 创作者，设计-0，编程-0，物理comp-0，制造-0，社区-0
interests: ''
technologies: rpi，物理计算，python
site_areas: ''
steps:
  - 
    title: 介绍
