---
title: Instaliranje Raspbian operacijskog sustava uz pomoć NOOBS instalacijskog programa
hero_image: images/banner.png
description: Vodič za instaliranje Raspbian operacijskog sustava, s bilo koje platforme, na SD karticu pomoću NOOBS instalacijskog programa
original_url: https://raspberrypi.org/learning/noobs-install
theme: red
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
  - 
    title: Uvod
