---
title: Instaliranje Raspbian s NOOBS
hero_image: slike / banner.png
description: Vodič o tome kako instalirati Raspbian na SD karticu pomoću NOOBS, s bilo koje platforme
original_url: https://raspberrypi.org/learning/noobs-install
theme: Crvena
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: kreator, dizajn-0, programiranje-0, fiz-comp-0, proizvodnja-0, community-0
interests: ''
technologies: rpi, fizičko računanje, python
site_areas: ''
steps:
  - 
    title: Uvod
