---
title: 'Raspbianin asentaminen NOOBS: iin'
hero_image: Kuvien / banner.png
description: 'Oppaita Raspbianin asentamisesta SD-kortille NOOBS: n avulla mistä tahansa alustasta'
original_url: https://raspberrypi.org/learning/noobs-install
theme: punainen
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: luoja, design-0, ohjelmointi-0, phys-comp-0, valmistus-0, yhteisö-0
interests: ''
technologies: rpi, fyysinen laskenta, python
site_areas: ''
steps:
  - 
    title: esittely
