---
title: Gosod Raspbian gyda NOOBS
hero_image: delweddau / banner.png
description: Canllaw ar sut i osod Raspbian ar gerdyn SD gan ddefnyddio NOOBS, o unrhyw lwyfan
original_url: https://raspberrypi.org/learning/noobs-install
theme: Coch
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: crewr, dylunio-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, cyfrifiadureg ffisegol, python
site_areas: ''
steps:
  - 
    title: Cyflwyniad
