---
title: Raspbian mit NOOBS installieren
hero_image: Bilder / Banner.png
description: Eine Anleitung zur Installation von Raspbian auf einer SD-Karte mit NOOBS von jeder Plattform aus
original_url: https://raspberrypi.org/learning/noobs-install
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: Schöpfer, Design-0, Programmierung-0, Phys-Comp-0, Herstellung-0, Community-0
interests: ''
technologies: rpi, physikalisches Rechnen, Python
site_areas: ''
steps:
  - 
    title: Einführung
