---
title: Instalando Raspbian com NOOBS
hero_image: images / banner.png
description: Um guia sobre como instalar o Raspbian em um cartão SD usando NOOBS, de qualquer plataforma
original_url: https://raspberrypi.org/learning/noobs-install
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: criador, design-0, programação-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, computação física, python
site_areas: ''
steps:
  - 
    title: Introdução
