---
title: Memasang Raspbian dengan NOOBS
hero_image: images / banner.png
description: Panduan tentang cara memasang Raspbian pada kartu SD menggunakan NOOBS, dari platform apa pun
original_url: https://raspberrypi.org/learning/noobs-install
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: pencipta, desain-0, pemrograman-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, komputasi fisik, python
site_areas: ''
steps:
  - 
    title: pengantar
