---
title: Instal·lant Raspbian amb NOOBS
hero_image: imatges / banner.png
description: Una guia sobre com instal·lar Raspbian en una targeta SD amb NOOBS, des de qualsevol plataforma
original_url: https://raspberrypi.org/learning/noobs-install
theme: vermell
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: creador, disseny-0, programació-0, phys-comp-0, fabricació-0, comunitat-0
interests: ''
technologies: rpi, informàtica física, pitó
site_areas: ''
steps:
  - 
    title: Introducció
