---
title: Namestitev Raspbian z NOOBS
hero_image: images / banner.png
description: Vodnik o namestitvi Raspbian na kartico SD z uporabo NOOBS-a, s katere koli platforme
original_url: https://raspberrypi.org/learning/noobs-install
theme: rdeča
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: ustvarjalec, design-0, programiranje-0, fiz-comp-0, izdelava-0, skupnost-0
interests: ''
technologies: rpi, fizično računanje, python
site_areas: ''
steps:
  - 
    title: Uvod
