---
title: Namestitev Raspbian s sistemom NOOBS
hero_image: images/banner.png
description: Vodnik o namestitvi sistema Raspbian na SD kartico z uporabo NOOBS-a s pomočjo katere koli platforme
original_url: https://raspberrypi.org/learning/noobs-install
theme: red
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
  - 
    title: Uvod
