---
title: התקנת Raspbian עם NOOBS
hero_image: תמונות / banner.png
description: מדריך על איך להתקין Raspbian על כרטיס SD באמצעות NOOBS, מכל פלטפורמה
original_url: https://raspberrypi.org/learning/noobs-install
theme: אָדוֹם
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: יוצר, עיצוב 0, תכנות 0, phys-comp-0, ייצור -0, קהילה -0
interests: ''
technologies: rpi, מחשוב פיזי, פיתון
site_areas: ''
steps:
  - 
    title: מבוא
