---
title: تثبيت Raspbian مع NOOBS
hero_image: صور / banner.png
description: دليل حول كيفية تثبيت Raspbian على بطاقة SD باستخدام NOOBS ، من أي نظام أساسي
original_url: https://raspberrypi.org/learning/noobs-install
theme: أحمر
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: الخالق ، design-0 ، programming-0 ، phys-comp-0 ، manufacture-0 ، community-0
interests: ''
technologies: rpi ، الحوسبة المادية ، python
site_areas: ''
steps:
  - 
    title: المقدمة
