---
title: Instalowanie Raspbian z NOOBS
hero_image: images / banner.png
description: Poradnik jak zainstalować Raspbian na karcie SD za pomocą NOOBS, z dowolnej platformy
original_url: https://raspberrypi.org/learning/noobs-install
theme: czerwony
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: twórca, design-0, programowanie-0, phys-comp-0, production-0, community-0
interests: ''
technologies: rpi, fizyczne przetwarzanie, python
site_areas: ''
steps:
  - 
    title: Wprowadzenie
