---
title: Installera Raspbian med NOOBS
hero_image: bilder/banderoll.png
description: En guide till hur du installerar Raspbian på ett SD-kort med hjälp av NOOBS, från vilken plattform som helst
original_url: https://raspberrypi.org/learning/noobs-install
theme: röd
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
  - 
    title: Introduktion
