---
title: নুব এর সাহায্যে রাস্পবিয়ান এর ইনস্টল করা
hero_image: ইমেজ/banner.png
description: যে কোনও প্ল্যাটফর্ম থেকে এসডি কার্ডে নুব এর সাহায্যে রাস্পবিয়ান কিভাবে ইন্সটল করা যায় সে সম্পর্কে একটি গাইড
original_url: https://raspberrypi.org/learning/noobs-install
theme: লাল
duration: 0
listed: false
ingredient: true
copyedit: false
curriculum: সৃষ্টিকর্তা , নকশা -0, প্রোগ্রামিং -0, phys-comp-0, উৎপাদন-0, কমিউনিটি -২0
interests: ''
technologies: rpi, ফিজিক্যাল কম্পিউটিং, পাইথন
site_areas: ''
steps:
  - 
    title: ভূমিকা
