---
title: Installation de Raspbian avec NOOBS
hero_image: images / banner.png
description: Un guide sur l'installation de Raspbian sur une carte SD en utilisant NOOBS, depuis n'importe quelle plateforme
original_url: https://raspberrypi.org/learning/noobs-install
theme: rouge
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: créateur, design-0, programmation-0, phys-comp-0, fabrication-0, communauté-0
interests: ''
technologies: rpi, informatique physique, python
site_areas: ''
steps:
  - 
    title: introduction
