---
title: Installazione di Raspbian con NOOBS
hero_image: images / banner.png
description: Una guida su come installare Raspbian su una scheda SD utilizzando NOOBS, da qualsiasi piattaforma
original_url: https://raspberrypi.org/learning/noobs-install
theme: rosso
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: creatore, design-0, programmazione-0, compatta-0, fabbricazione-0, comunità-0
interests: ''
technologies: rpi, calcolo fisico, python
site_areas: ''
steps:
  - 
    title: introduzione
