---
title: NOOBS මගින් Raspbian ස්ථාපනය කිරීම
hero_image: images / banner.png
description: මෙය ඕනෑම වේදිකාවක(platform එකක) සිට NOOBS භාවිතා කරමින් SD කාඩ් පතක Raspbian ස්ථාපනය(install) කරන්නේ කෙසේද යන්න පිළිබඳ මාර්ගෝපදේශයකි
original_url: https://raspberrypi.org/learning/noobs-install
theme: රතු
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: නිර්මාණකරු, සැලසුම්-0, කේතන වැඩසටහන්-0, භෞතික-පරිගනක-0, නිෂ්පාදනය-0, ප්‍රජා-0
interests: ''
technologies: rpi, භෞතික පරිගණක කරණය, python
site_areas: ''
steps:
  - 
    title: හැදින්වීම
